const Data = [
  {
    key: 1,
    name: "github",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-github",
  },

  {
    key: 2,
    name: "facebook",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-facebook",
  },

  {
    key: 3,
    name: "twitter",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-twitter",
  },
  {
    key: 4,
    name: "twitch",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-twitch",
  },
  {
    key: 5,
    name: "instagram",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-instagram",
  },
  {
    key: 6,
    name: "circle",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-circle",
  },
  {
    key: 7,
    name: "square",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-square",
  },
  {
    key: 8,
    name: "tractor",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-tractor",
  },
  {
    key: 9,
    name: "car",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-car",
  },
  {
    key: 10,
    name: "behance",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-behance",
  },
  {
    key: 11,
    name: "blogger",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-blogger",
  },
  {
    key: 12,
    name: "android",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-android",
  },
  {
    key: 13,
    name: "apple",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-apple-whole",
  },
  {
    key: 14,
    name: "visa",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-cc-visa",
  },
  {
    key: 15,
    name: "aws",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-aws",
  },
  {
    key: 16,
    name: "discord",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-discord",
  },
  {
    key: 17,
    name: "bag",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-bag-shopping",
  },
  {
    key: 18,
    name: "baseball",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-baseball",
  },
  {
    key: 19,
    name: "git",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-git",
  },
  {
    key: 20,
    name: "bell",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-bell",
  },
  {
    key: 21,
    name: "bicycle",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-bicycle",
  },
  {
    key: 22,
    name: "medical",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-briefcase-medical",
  },
  {
    key: 23,
    name: "bucket",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-bucket",
  },
  {
    key: 24,
    name: "burger",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-burger",
  },
  {
    key: 25,
    name: "react",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-react",
  },
];

export default Data;
