const Data = [
  {
    key: 1,
    name: "github",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-github",
  },

  {
    key: 2,
    name: "facebook",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-facebook",
  },

  {
    key: 3,
    name: "twitter",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-twitter",
  },
  {
    key: 4,
    name: "twitch",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-twitch",
  },
  {
    key: 5,
    name: "instagram",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-instagram",
  },
  {
    key: 6,
    name: "circle",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-circle",
  },
  {
    key: 7,
    name: "square",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-square",
  },
  {
    key: 8,
    name: "tractor",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-tractor",
  },
  {
    key: 9,
    name: "car",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-car",
  },
  {
    key: 10,
    name: "behance",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-behance",
  },
  {
    key: 11,
    name: "blogger",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-blogger",
  },
  {
    key: 12,
    name: "android",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-android",
  },
  {
    key: 13,
    name: "apple",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-apple-whole",
  },
  {
    key: 14,
    name: "visa",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-cc-visa",
  },
  {
    key: 15,
    name: "aws",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-aws",
  },
  {
    key: 16,
    name: "discord",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-discord",
  },
  {
    key: 17,
    name: "bag",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-bag-shopping",
  },
  {
    key: 18,
    name: "baseball",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-baseball",
  },
  {
    key: 19,
    name: "git",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-git",
  },
  {
    key: 20,
    name: "bell",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-bell",
  },
  {
    key: 21,
    name: "bicycle",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-bicycle",
  },
  {
    key: 22,
    name: "medical",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-briefcase-medical",
  },
  {
    key: 23,
    name: "bucket",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-bucket",
  },
  {
    key: 24,
    name: "burger",
    isFlipped: false,
    isMatched: false,
    url: "fa-solid fa-burger",
  },
  {
    key: 25,
    name: "react",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-react",
  },
  {
    key: 26,
    name: "bluetooth",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-bluetooth",
  },
  {
    key: 27,
    name: "bitcoin",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-bitcoin",
  },
  {
    key: 28,
    name: "chrome",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-chrome",
  },
  {
    key: 29,
    name: "stripe",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-cc-stripe",
  },
  {
    key: 30,
    name: "css",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-css3-alt",
  },
  {
    key: 31,
    name: "firefox",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-firefox",
  },
  // for testing
  {
    key: 32,
    name: "figma",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-figma",
  },
  {
    key: 33,
    name: "imdb",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-imdb",
  },
  {
    key: 34,
    name: "itunes",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-itunes",
  },
  {
    key: 35,
    name: "line",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-line",
  },
  {
    key: 36,
    name: "microsoft",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-microsoft",
  },
  {
    key: 37,
    name: "octopus",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-octopus-deploy",
  },
  {
    key: 38,
    name: "php",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-php",
  },
  {
    key: 39,
    name: "python",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-python",
  },
  {
    key: 40,
    name: "reddit",
    isFlipped: false,
    isMatched: false,
    url: "fa-brands fa-reddit",
  },
];

export default Data;
